"""add article summary and recommend_score

Revision ID: 56da8db640ae
Revises: 1477541626a8
Create Date: 2026-10-06 22:46:28.262966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56da8db640ae'
down_revision: Union[str, Sequence[str], None] = '1477541626a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('summary', sa.Text(), nullable=True, comment='AI 摘要'))
    op.add_column('article', sa.Column('recommend_score', sa.Integer(), nullable=True, comment='AI 推荐值，1~10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'recommend_score')
    op.drop_column('article', 'summary')
    # ### end Alembic commands ###
